name: Compile Qt project

on: push

env:
  BUILD_TYPE: Release
  QT_VERSION: '6.8.0'
  VCPKG_ROOT: '${{ github.workspace }}/vcpkg'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get cmake
      uses: lukka/get-cmake@latest

    - uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: ${{ env.QT_VERSION }}
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        tools: 'tools_ninja tools_cmake tools_vcredist,qt.tools.vcredist_msvc2022_x64'

    - name: Configure CMake
      run: cmake -B build -S . -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -B ${{github.workspace}}/build

    # 编译解决方案
    - name: Build Solution
      run: |
        cd ${{ github.workspace }}
        cd build
        cmake --build . --parallel --config Release

    - name: get dir tree
      run: |
        cd ${{ github.workspace }}
        tree /f > tree.txt

    - name: Upload dir tree
      uses: actions/upload-artifact@v4
      with:
        name: tree.txt
        path: ${{ github.workspace }}/tree.txt

    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
        name: AutoGo.exe
        path: ${{ github.workspace }}/build/Release/AutoGo.exe
